### Site Settings ###
remote_theme: "yousinix/portfolYOU"
title: "Oğuzhan Daşkaya"
description: "A man never going to stop learning"
baseurl: ""
repository: "ozhan77/ozhan77.github.io"
open_new_tab: true

plugins:
  - jemoji

nav_exclude:
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/**

author:
  name: Oğuzhan Daşkaya
  image: https://avatars.githubusercontent.com/u/66035997?s=400&u=a79dda5a831bb383bdc85c1dbafebab215a25372&v=4
  email: oguzhandky@gmail.com
  github: ozhan77
  linkedin: oguzhan-daskaya
  psxplace: members/el_isra.59064/


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  elements:
    output: true



disqus:
  shortname: oguzhan


### Analytics ###
analytics:
  enabled: false
  google:
    tracking_id: your-google-tracking-id


### Buy me a coffee ###
# See https://www.buymeacoffee.com/
#buymeacoffee:
#  enabled: false
#  username: your_username
#  color: "#007bff"
#  message: "Thank you for visiting."                    # Message to be displayed aside from the button for a few seconds.
#  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "elements"
    values:
      layout: "element"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments



exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
